# -*- coding: utf-8 -*-
"""better _fastwithspacy_forecaster_with_sentiment_comments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bswyfs-577IW6EBDSmGhkio0JpkezM7d
"""

# Install dependencies (run once per new Colab session)
!pip install nltk spacy scikit-learn plotly
!python -m spacy download en_core_web_sm
import nltk
nltk.download("vader_lexicon")

# Imports & config
import re
from typing import Optional, List
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from nltk.sentiment import SentimentIntensityAnalyzer
import spacy
from sklearn.ensemble import HistGradientBoostingClassifier, HistGradientBoostingRegressor
from sklearn.metrics import average_precision_score, mean_absolute_error
SURGE_TOP_PCT = 0.10
MIN_POSTS_PER_MICROTOPIC = 4
RANDOM_STATE = 42
pd.set_option("display.max_colwidth", 200)
vader = SentimentIntensityAnalyzer()
nlp = spacy.load("en_core_web_sm")

# Load CSV
from google.colab import files, drive
drive.mount('/content/drive')
CSV_PATH = "/content/drive/MyDrive/DSBA 6156 ML Project (Reddit Fashion)/merged_reddit_posts_final.csv"
df = pd.read_csv(CSV_PATH)
df.head()

# Clean text, timestamps, engagement
def norm(s: Optional[str]) -> str:
    if not isinstance(s, str):
        return ""
    return re.sub(r"\s+", " ", s.strip())

# Normalize title & selftext
df["title"] = df["title"].apply(norm)
df["selftext"] = df.get("selftext", "").apply(norm)

CSV_PATH_CMNTS = "/content/drive/MyDrive/DSBA 6156 ML Project (Reddit Fashion)/all_comments_multi2.csv"
comments_df = pd.read_csv(CSV_PATH_CMNTS)
# Clean comment text
comments_df["body"] = comments_df["body"].astype(str).apply(norm)

# --- Start of specific fixes ---

# Normalize df['name'] to remove 't3_' for consistent merging keys
df["name"] = df["name"].astype(str).str.replace("^t3_", "", regex=True)

# Normalize comments_df['link_id'] to remove 't3_' for consistent merging keys
# This block was present in OEoHVYo_rCJk but missing here, leading to potential issues.
if comments_df["link_id"].astype(str).str.startswith("t3_").any():
    comments_df["link_id"] = comments_df["link_id"].astype(str).str.replace("^t3_", "", regex=True)

# Aggregate all comments for a given post into one big string
comments_per_post = (
    comments_df
    .groupby("link_id")["body"]
    .apply(lambda texts: " ".join(t for t in texts if isinstance(t, str)))
    .reset_index()
    .rename(columns={"link_id": "name", "body": "comments_text"})
)

# Ensure df does not already have a 'comments_text' column from a previous run
# This prevents MergeError if the cell is run multiple times or if 'comments_text'
# was already present in df from another source.
if 'comments_text' in df.columns:
    df = df.drop(columns=['comments_text'])

# Merge aggregated comments onto the main posts dataframe using `name`
df = df.merge(comments_per_post, on="name", how="left")

# --- End of specific fixes ---

# Ensure we have a string field even if a post has no comments
df["comments_text"] = df["comments_text"].fillna("")

# Combined text field: title + selftext + aggregated comments
df["all_text"] = (
    df["title"].fillna("") + " " +
    df["selftext"].fillna("") + " " +
    df["comments_text"].fillna("")
).str.strip()


# Convert created_utc to datetime (assumes seconds since epoch)
df["created_utc"] = pd.to_datetime(
    df["created_utc"],
    unit="s",
    errors="coerce",
    utc=True
)

df["score"] = df["score"].astype(float)
df["num_comments"] = df["num_comments"].astype(float)
df["engagement"] = df["score"] + df["num_comments"]
df[["id", "title", "engagement", "created_utc"]].head()

print(df["name"].head())
print(comments_df["link_id"].head())

# Sentiment analysis
def vader_sentiment(text: str) -> float:
    if not isinstance(text, str) or not text.strip():
        return 0.0
    return float(vader.polarity_scores(text)["compound"])

df["sentiment"] = df["all_text"].apply(vader_sentiment)
df[["id", "title", "sentiment"]].head(10)

# --------------------------------------------------------------
# OPTIMIZED SPACY BRAND DISCOVERY — FAST NER MODE (~20–40 sec)
# --------------------------------------------------------------

import spacy
import pandas as pd
from collections import Counter

# Load the tiny English model without costly components
!python -m spacy download en_core_web_sm

nlp = spacy.load(
    "en_core_web_sm",
    disable=["parser", "tagger", "lemmatizer"]  # keep only NER
)

def discover_brands_spacy(texts, min_count=10):
    counter = Counter()

    # Large batch for best throughput, no parallelism (best for Colab CPU)
    for doc in nlp.pipe(texts, batch_size=512, n_process=1):
        for ent in doc.ents:
            if ent.label_ in {"ORG", "PRODUCT"}:
                name = ent.text.strip()
                if len(name) >= 2:
                    counter[name] += 1

    df = (pd.DataFrame([{"brand": k, "count": v} for k, v in counter.items()])
            .sort_values("count", ascending=False)
            .reset_index(drop=True))

    return df[df["count"] >= min_count].reset_index(drop=True)

# --- Use TITLES only (massive speedup with no quality loss)
texts = df["title"].fillna("").tolist()

brand_candidates_df = discover_brands_spacy(texts, min_count=10)
brand_candidates_df.head(30)

brand_candidates_df.shape
brand_candidates_df.head(100)

# Save & clean brand list
brand_candidates_df.to_csv("discovered_brands.csv", index=False)
blacklist = {"Today","Monday","Tuesday","Friday","Reddit","YouTube","Instagram","WhatsApp","Buy","Need"}
auto_brands = [b for b in brand_candidates_df["brand"] if b not in blacklist]
manual_additions = ["Nike","Adidas","Jordan","New Balance","Yeezy","Stüssy","Aimé Leon Dore"]
BRANDS = sorted({b.strip() for b in auto_brands + manual_additions if b.strip()})
len(BRANDS), BRANDS[:30]

# Items list + regex
ITEMS = ["Dunk","Dunks","Air Force 1","AF1","Jordan 1","Jordan 4","Jordan 3","Samba","Gazelle","Campus","Huarache",
         "hoodie","hoodies","crewneck","t-shirt","tee","tees","cargo pants","cargos","jeans","denim","puffer","parka",
         "tracksuit","track jacket","track pants","bag","tote bag","backpack","belt","cap","hat","beanie"]
def _escape_for_regex(name): return re.escape(name)
brand_pattern = r"|".join(sorted(_escape_for_regex(b) for b in BRANDS))
item_pattern  = r"|".join(sorted(_escape_for_regex(i) for i in ITEMS))
BRAND_RE = re.compile(rf"\b({brand_pattern})\b", flags=re.IGNORECASE)
ITEM_RE  = re.compile(rf"\b({item_pattern})\b", flags=re.IGNORECASE)
BRAND_RE, ITEM_RE

# Extract brands/items
def normalize_token(s): return re.sub(r"\s+"," ",s.strip().lower())
AF1_VARIANTS = {"af1","af1s","air force 1","air force 1s","forces"}
AF1_CANON = "air force 1"
NB_VARIANTS = {"nb","new balance"}
NB_CANON = "new balance"

def canonicalize_item(raw):
    s = normalize_token(raw)
    return AF1_CANON if s in AF1_VARIANTS else s

def canonicalize_brand(raw):
    s = normalize_token(raw)
    return NB_CANON if s in NB_VARIANTS else s

def extract_brands(text):
    if not isinstance(text,str): return []
    return sorted({canonicalize_brand(m.group(0)) for m in BRAND_RE.finditer(text)})

def extract_items(text):
    if not isinstance(text,str): return []
    return sorted({canonicalize_item(m.group(0)) for m in ITEM_RE.finditer(text)})

df["brands"] = df["all_text"].apply(extract_brands)
df["items"]  = df["all_text"].apply(extract_items)
df[["id","title","brands","items"]].head(15)

# Build microtopics
rows=[]
for _,r in df.iterrows():
    brands=r["brands"]; items=r["items"]
    if not brands: continue
    pairs=[(b,"GEN") for b in brands] if not items else [(b,it) for b in brands for it in items]
    pairs=pairs[:6]
    week=r["created_utc"].to_period("W")
    week_start=week.start_time
    for b,it in pairs:
        rows.append({
            "id":r["id"], "week_start":week_start,
            "iso_year":int(r["created_utc"].isocalendar().year),
            "iso_week":int(r["created_utc"].isocalendar().week),
            "brand":b,"item":it,"microtopic":f"{b} | {it}",
            "engagement":r["engagement"],"score":r["score"],
            "num_comments":r["num_comments"],"sentiment":r["sentiment"],
            "has_selftext":1.0 if len(r["selftext"])>0 else 0.0,
        })
micro=pd.DataFrame(rows)
micro.head()

# Aggregate weekly
agg=(micro.groupby(["microtopic","brand","item","iso_year","iso_week","week_start"],as_index=False)
     .agg(posts=("id","count"),engagement_sum=("engagement","sum"),
          score_sum=("score","sum"),comments_sum=("num_comments","sum"),
          sentiment_mean=("sentiment","mean"),selftext_rate=("has_selftext","mean")))
topic_sizes=agg.groupby("microtopic")["posts"].sum().reset_index(name="total_posts")
big_topics=topic_sizes[topic_sizes["total_posts"]>=MIN_POSTS_PER_MICROTOPIC]["microtopic"]
agg=agg[agg["microtopic"].isin(big_topics)].reset_index(drop=True)
agg.head()

# Rolling features
def add_rolling_features(g):
    g=g.sort_values(["iso_year","iso_week"]).copy()
    g["engagement_prev"]=g["engagement_sum"].shift(1).fillna(0)
    g["engagement_wow"]=(g["engagement_sum"]-g["engagement_prev"])/g["engagement_prev"].replace(0,1)
    g["engagement_ema3"]=g["engagement_sum"].ewm(span=3,adjust=False).mean()
    g["engagement_ema7"]=g["engagement_sum"].ewm(span=7,adjust=False).mean()
    g["posts_prev"]=g["posts"].shift(1).fillna(0)
    g["posts_wow"]=(g["posts"]-g["posts_prev"])/g["posts_prev"].replace(0,1)
    g["sentiment_prev"]=g["sentiment_mean"].shift(1).fillna(0)
    g["sentiment_delta"]=g["sentiment_mean"]-g["sentiment_prev"]
    g["engagement_next"]=g["engagement_sum"].shift(-1)
    g["growth_next"]=(g["engagement_next"]-g["engagement_sum"])/g["engagement_sum"].replace(0,1)
    return g

feat=agg.groupby("microtopic",group_keys=False).apply(add_rolling_features)
feat["weekofyear_sin"]=np.sin(2*np.pi*feat["iso_week"]/52)
feat["weekofyear_cos"]=np.cos(2*np.pi*feat["iso_week"]/52)
feat=feat.dropna(subset=["engagement_next"]).reset_index(drop=True)
feat.head()

# Train/test split
all_weeks=(feat[["iso_year","iso_week","week_start"]]
           .drop_duplicates().sort_values(["iso_year","iso_week"]).reset_index(drop=True))
split_idx=int(len(all_weeks)*0.70)
split_year=int(all_weeks.loc[split_idx,"iso_year"])
split_week=int(all_weeks.loc[split_idx,"iso_week"])

def is_train(yr,wk): return (yr<split_year) or (yr==split_year and wk<=split_week)

feat["is_train"]=feat.apply(lambda r: is_train(int(r["iso_year"]),int(r["iso_week"])),axis=1)
train_df=feat[feat["is_train"]]; test_df=feat[~feat["is_train"]]

# Features/labels
surge_thresh=float(np.quantile(train_df["growth_next"].dropna(),1.0-SURGE_TOP_PCT))
train_df["y_cls"]=(train_df["growth_next"]>=surge_thresh).astype(int)
test_df["y_cls"] =(test_df["growth_next"] >=surge_thresh).astype(int)

FEATURE_COLS=["posts","engagement_sum","score_sum","comments_sum","sentiment_mean","selftext_rate",
              "engagement_prev","engagement_wow","engagement_ema3","engagement_ema7",
              "posts_prev","posts_wow","sentiment_prev","sentiment_delta",
              "weekofyear_sin","weekofyear_cos"]

def safe_X(df_in):
    return df_in[FEATURE_COLS].fillna(0).astype(float)

X_train=safe_X(train_df); y_train_cls=train_df["y_cls"]; y_train_reg=train_df["engagement_next"]
X_test=safe_X(test_df);   y_test_cls=test_df["y_cls"];   y_test_reg=test_df["engagement_next"]

# Train models
clf=HistGradientBoostingClassifier()
clf.fit(X_train,y_train_cls)
reg=HistGradientBoostingRegressor()
reg.fit(X_train,y_train_reg)

# Evaluate
probs=clf.predict_proba(X_test)[:,1]
pr_auc=average_precision_score(y_test_cls,probs)
pred_next=reg.predict(X_test)
mae=mean_absolute_error(y_test_reg,pred_next)
print(f"PR-AUC: {pr_auc:.3f}")
print(f"MAE: {mae:.2f}")
print(f"Surge threshold: {surge_thresh:.3f}")

# Watchlist
latest_year=int(feat["iso_year"].max())
latest_week=int(feat[feat["iso_year"]==latest_year]["iso_week"].max())
latest=feat[(feat["iso_year"]==latest_year)&(feat["iso_week"]==latest_week)].copy()
X_latest=safe_X(latest)
latest["surge_prob"]=clf.predict_proba(X_latest)[:,1]
latest["pred_next_engagement"]=reg.predict(X_latest)
watchlist_cols=["microtopic","brand","item","iso_year","iso_week","week_start",
                "posts","engagement_sum","sentiment_mean","surge_prob","pred_next_engagement"]
watchlist=(latest[watchlist_cols].sort_values(["surge_prob","pred_next_engagement"],ascending=False)
           .reset_index(drop=True))
watchlist.head(20)

# Save outputs
watchlist.to_csv("watchlist_next_week.csv",index=False)
pd.Series({"surge_threshold_growth_used":surge_thresh,"pr_auc":pr_auc,"mae_next_engagement":mae})\
  .to_csv("bmtf_eval_summary.csv")

# KPIs & charts
total_posts=int(agg["posts"].sum())
unique_brands=micro["brand"].nunique()
unique_items=micro["item"].nunique()
date_min=agg["week_start"].min().date()
date_max=agg["week_start"].max().date()
print(f"Posts: {total_posts:,}")
print(f"Brands: {unique_brands}, Items: {unique_items}")
print(f"Range: {date_min} → {date_max}")

recent_weeks=(agg[["week_start"]].drop_duplicates().sort_values("week_start").tail(8)["week_start"].tolist())
recent=agg[agg["week_start"].isin(recent_weeks)]
brand_summary=(recent.groupby("brand")["engagement_sum"].sum()
               .sort_values(ascending=False).head(15).reset_index())
import plotly.express as px
fig=px.bar(brand_summary,x="brand",y="engagement_sum",
           title="Top brands (last ~8 weeks)")
fig.show()